ecsite_project/accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView, HomeView, UserLoginView,
    UserLogoutView, UserView
)

app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user/', UserView.as_view(), name='user'),
]

ecsite_project/ecsite_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('stores/',include('stores.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

ecsite_project/stores/urls.py
from django.urls import path
from .views import(
    ProductListView,ProductDetailView,
    add_product,CartItemsView,CartUpdateView,
    CartDeleteView,InputAddressView,ConfirmOrderView,
    OrderSuccessView
)

app_name = 'stores'
urlpatterns = [
    path('product_list/',ProductListView.as_view(),name='product_list'),
    path('product_detail/<int:pk>',ProductDetailView.as_view(),name='product_detail'),
    path('add_product/',add_product,name='add_product'),
    path('cart_items/',CartItemsView.as_view(),name='cart_items'),
    path('update_cart/<int:pk>',CartUpdateView.as_view(),name='update_cart'),
    path('delete_cart/<int:pk>',CartDeleteView.as_view(),name='delete_cart'),
    path('input_address/',InputAddressView.as_view(),name='input_address'),
    path('input_address/<int:pk>',InputAddressView.as_view(),name='input_address'),
    path('confirm_order/',ConfirmOrderView.as_view(),name='confirm_order'),
    path('order_success/',OrderSuccessView.as_view(),name='order_success'),
]

ecsite_project/templates/base.html
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
        <a class="navbar-brand" href="{% url 'stores:product_list' %}">商品一覧</a>
        <a class="navbar-brand" href="{% url 'stores:cart_items' %}">カートへ</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
        <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>
        {% endif %}
      </nav>
      {% block content %}{% endblock %}
   </body>
</html>

ecsite_project/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>ホーム画面です</h1>
{% endblock %}

ecsite_project/templates/regist.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="ユーザ登録">
</form>
{% endblock %}

ecsite_project/templates/user.html
{% extends 'base.html' %}
{% block content %}
<h1>ユーザ画面です。ログインが必要な画面です</h1>
{% endblock %}

ecsite_project/templates/user_login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="hidden" name="next" value="{{ request.GET.next }}">
   <input type="submit" value="ログイン">
</form>
{% endblock %}