ecsite_project/ecsite_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('stores/',include('stores.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

ecsite_project/stores/urls.py
from django.urls import path
from .views import(
    ProductListView,ProductDetailView,
    add_product,CartItemsView,CartUpdateView,
    CartDeleteView,InputAddressView,ConfirmOrderView,
    OrderSuccessView
)

app_name = 'stores'
urlpatterns = [
    path('product_list/',ProductListView.as_view(),name='product_list'),
    path('product_detail/<int:pk>',ProductDetailView.as_view(),name='product_detail'),
    path('add_product/',add_product,name='add_product'),
    path('cart_items/',CartItemsView.as_view(),name='cart_items'),
    path('update_cart/<int:pk>',CartUpdateView.as_view(),name='update_cart'),
    path('delete_cart/<int:pk>',CartDeleteView.as_view(),name='delete_cart'),
    path('input_address/',InputAddressView.as_view(),name='input_address'),
    path('input_address/<int:pk>',InputAddressView.as_view(),name='input_address'),
    path('confirm_order/',ConfirmOrderView.as_view(),name='confirm_order'),
    path('order_success/',OrderSuccessView.as_view(),name='order_success'),
]

ecsite_project/stores/models.py
from django.db import models
from accounts.models import Users



class ProductTypes(models.Model):
    name = models.CharField(max_length=1000)
    
    class Meta:
        db_table = 'product_types'
        
    def __str__(self):
        return self.name
    

class Manufacturers(models.Model):
    name = models.CharField(max_length=1000)
    
    class Meta:
        db_table = 'manufacturers'
        
    def __str__(self):
        return self.name

class ProductsManager(models.Manager):
    def reduce_stock(self,cart):
        for item in cart.cartitems_set.all():
            update_stock = item.product.stock - item.quantity
            item.product.stock = update_stock
            item.product.save()
    
    
class Products(models.Model):
    name = models.CharField(max_length=1000)
    price = models.IntegerField()
    stock = models.IntegerField()
    product_type = models.ForeignKey(
        ProductTypes,on_delete=models.CASCADE
    )
    manufacturer = models.ForeignKey(
        Manufacturers,on_delete=models.CASCADE
    )
    objects = ProductsManager()
    
    class Meta:
        db_table = 'products'
        
    def __str__(self):
        return self.name
    

class ProductPictures(models.Model):
    picture = models.FileField(upload_to='product_pictures/')
    product = models.ForeignKey(
        Products,on_delete=models.CASCADE
    )
    order = models.IntegerField()
    
    class Meta:
        db_table = 'product_pictures'
        ordering = ['order']
        
    def __str__(self):
        return self.product.name + ' : ' + str(self.order)
    

class Carts(models.Model):
    user = models.OneToOneField(
        Users,
        on_delete=models.CASCADE,
        primary_key =True
    )
    
    class Meta:
        db_table = 'carts'
        
class CartItemsManager(models.Manager):
    
    def save_item(self,product_id,quantity,cart):
        c = self.model(quantity=quantity,product_id=product_id,cart=cart)
        c.save()


class CartItems(models.Model):
    quantity = models.PositiveIntegerField()
    product = models.ForeignKey(
        Products,on_delete=models.CASCADE
    )
    cart = models.ForeignKey(
        Carts,on_delete=models.CASCADE     
    )
    objects = CartItemsManager()
    
    class Meta:
        db_table = 'cart_items'
        unique_together = [['product','cart']]
        
class Addresses(models.Model):
    zip_code = models.CharField(max_length=8)
    prefecture = models.CharField(max_length=10)
    address = models.CharField(max_length=100)
    user = models.ForeignKey(
        Users,
        on_delete = models.CASCADE,
    )
    
    class Meta:
        db_table = 'addresses'
        unique_together = [
            ['zip_code','prefecture','address','user']
        ]
        
    def __str__(self):
        return f'{self.zip_code} {self.prefecture} {self.address}'

class OrdersManager(models.Manager):
    
    def insert_cart(self,cart:Carts,address,total_price):
        return self.create(
            total_price=total_price,
            address=address,
            user=cart.user,
        )

    
class Orders(models.Model):
    total_price = models.PositiveIntegerField()
    address = models.ForeignKey(
        Addresses,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    user = models.ForeignKey(
        Users,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    objects = OrdersManager()
    
    class Meta:
        db_table = 'orders'
        
class OrderItemsManager(models.Manager):
    
    def insert_cart_items(self,cart,order):
        for item in cart.cartitems_set.all():
            self.create(
                quantity=item.quantity,
                product=item.product,
                order=order
            )
    
        
class OrderItems(models.Model):
    quantity = models.PositiveIntegerField()
    product = models.ForeignKey(
        Products,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    order = models.ForeignKey(
        Orders,
        on_delete=models.CASCADE
    )
    objects = OrderItemsManager()
    
    class Meta:
        db_table = 'order_items'
        unique_together = [['product','order']]
        

ecsite_project/stores/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
from .models import Addresses,CartItems
from django.core.cache import cache

class CartUpdateForm(forms.ModelForm):
    quantity = forms.IntegerField(label ='数量',min_value=1)
    id = forms.CharField(widget=forms.HiddenInput())
    
    class Meta:
        model = CartItems
        fields = ['quantity','id']
        
    def clean(self):
        cleaned_data = super().clean()
        quantity = cleaned_data.get('quantity')
        id = cleaned_data.get('id')
        cart_item = get_object_or_404(CartItems,pk=id)
        if quantity > cart_item.product.stock:
            raise ValidationError(f'在庫数を超えています。{cart_item.product.stock}以下にしてください')
        

class AddressInputForm(forms.ModelForm):
    address = forms.CharField(label='住所',widget=forms.TextInput(attrs={'size':'80'}))
    
    class Meta:
        model = Addresses
        fields = ['zip_code','prefecture','address']
        labels = {
            'zip_code':'郵便番号',
            'prefecture':'都道府県',
        }
        
    def save(self):
        address = super().save(commit=False)
        address.user = self.user
        try:
            address.validate_unique()
            address.save()
        except ValidationError as e:
            address = get_object_or_404(
                Addresses,user=self.user,
                prefecture=address.prefecture,
                zip_code=address.zip_code,
                address=address.address
            )
            pass
        cache.set(f'address_user_{self.user.id}',address)
        return address
        
        

ecsite_project/stores/views.py
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse,Http404
from django.views.generic.base import TemplateView
from django.views.generic.edit import(
    UpdateView,DeleteView,CreateView
)
from django.urls import reverse_lazy
from django.core.cache import cache
from django.db import transaction

import os
from .models import(
    Products,Carts,CartItems,Addresses,
    Orders,OrderItems,
)
from .forms import(
    CartUpdateForm,AddressInputForm
)

class ProductListView(LoginRequiredMixin,ListView):
    model = Products
    template_name = os.path.join('stores','product_list.html')
    
    def get_queryset(self):
        query = super().get_queryset()
        product_type_name = self.request.GET.get('product_type_name',None)
        product_name = self.request.GET.get('product_name',None)
        if product_type_name:
            query = query.filter(
                product_type__name=product_type_name
            )
        if product_name:
            query = query.filter(
                name=product_name
            )
        order_by_price = self.request.GET.get('order_by_price',0)
        if order_by_price == '1':
            query = query.order_by('price')
        elif order_by_price == '2':
            query = query.order_by('-price')
        return query
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_type_name']= self.request.GET.get('product_type_name','')
        context['product_name']= self.request.GET.get('product_name','')
        order_by_price = self.request.GET.get('order_by_price',0)
        if order_by_price == '1':
            context['ascending'] = True
        elif order_by_price == '2':
            context['descending'] = True
        return context
    
class ProductDetailView(LoginRequiredMixin,DetailView):
    model = Products
    template_name = os.path.join('stores','product_detail.html')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_added'] = CartItems.objects.filter(
            cart_id=self.request.user.id,
            product_id=kwargs.get('object').id
        ).first()
        return context


@login_required
def add_product(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        product_id = request.POST.get('product_id')
        quantity = request.POST.get('quantity')
        product = get_object_or_404(Products,id=product_id)
        if int(quantity) > product.stock:
            response = JsonResponse({'message':'在庫を超えています'})
            response.status_code = 403
            return response
        if int(quantity) <= 0:
            response = JsonResponse({'message':'0より大きい値を入力してください'})
            response.status_code = 403
            return response
        cart = Carts.objects.get_or_create(
            user=request.user
        )
        if all([product_id,cart,quantity]):
            CartItems.objects.save_item(
                quantity=quantity,product_id=product_id,
                cart=cart[0]
            )
            return JsonResponse({'message':'商品をカートに追加しました'})
        
class CartItemsView(LoginRequiredMixin,TemplateView):
    template_name = os.path.join('stores','cart_items.html')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id
        query = CartItems.objects.filter(cart_id=user_id)
        total_price = 0
        items = []
        for item in query.all():
            total_price += item.quantity * item.product.price
            picture = item.product.productpictures_set.first()
            picture = picture.picture if picture else None
            in_stock = True if item.product.stock >=item.quantity else False
            tmp_item = {
                'quantity':item.quantity,
                'picture':picture,
                'name':item.product.name,
                'id':item.id,
                'price':item.product.price,
                'in_stock':in_stock,
            }
            items.append(tmp_item)
            
        context['total_price'] = total_price
        context['items'] = items
        return context
    

class CartUpdateView(LoginRequiredMixin,UpdateView):
    template_name = os.path.join('stores','update_cart.html')
    form_class = CartUpdateForm
    model = CartItems
    success_url = reverse_lazy('stores:cart_items')
    
    
class CartDeleteView(LoginRequiredMixin,DeleteView):
    template_name = os.path.join('stores','delete_cart.html')
    model = CartItems
    success_url = reverse_lazy('stores:cart_items')
    

class InputAddressView(LoginRequiredMixin,CreateView):
    template_name = os.path.join('stores','input_address.html')
    form_class = AddressInputForm
    success_url = reverse_lazy('stores:confirm_order')
    
    def get(self,request,pk=None):
        cart = get_object_or_404(Carts,user_id=request.user.id)
        if not cart.cartitems_set.all():
            raise Http404('商品が入っていません')
        return super().get(request,pk)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        address = cache.get(f'address_user_{self.request.user.id}')
        pk = self.kwargs.get('pk')
        address = get_object_or_404(Addresses,user_id=self.request.user.id,pk=pk) if pk else address
        if address:
            context['form'].fields['zip_code'].initial = address.zip_code
            context['form'].fields['prefecture'].initial = address.prefecture
            context['form'].fields['address'].initial = address.address
        context['addresses'] = Addresses.objects.filter(user=self.request.user).all()
        return context                    
    
    def form_valid(self, form):
        form.user = self.request.user
        return super().form_valid(form)
    
class ConfirmOrderView(LoginRequiredMixin,TemplateView):
    template_name = os.path.join('stores','confirm_order.html')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        address = cache.get(f'address_user_{self.request.user.id}')
        context['address'] = address
        cart = get_object_or_404(Carts,user_id=self.request.user.id)
        context['cart'] =cart
        total_price = 0
        items = []
        for item in cart.cartitems_set.all():
            total_price += item.quantity * item.product.price
            picture = item.product.productpictures_set.first()
            picture = picture.picture if picture else None
            tmp_item = {
                'quantity':item.quantity,
                'picture':picture,
                'name':item.product.name,
                'price':item.product.price,
                'id':item.id,
            }
            items.append(tmp_item)
        context['total_price'] = total_price
        context['items'] = items
        return context
    
    @transaction.atomic
    def post(self,request,*args,**kwargs):
        context = self.get_context_data()
        address = context.get('address')
        cart = context.get('cart')
        total_price = context.get('total_price')
        if (not address) or (not cart) or (not total_price):
            raise Http404('注文処理でエラーが発生しました')
        for item in cart.cartitems_set.all():
            if item.quantity > item.product.stock:
                raise Http404('注文処理でエラーが発生しました')
        order = Orders.objects.insert_cart(cart,address,total_price)
        OrderItems.objects.insert_cart_items(cart,order)
        Products.objects.reduce_stock(cart)
        cart.delete()
        return redirect(reverse_lazy('stores:order_success'))
    
    
class OrderSuccessView(LoginRequiredMixin,TemplateView):
    
    template_name = os.path.join('stores','order_success.html')
    

ecsite_project/templates/stores/cart_items.html
{% extends 'base.html' %}
{% block content %}
<div class="col-10 offset-1">
{% if items %}
<table>
<tbody>
{% for item in items %}
   <tr>
     <td style="width:20%">
     {% if item.picture %}
     <img width="75px" height="75px" src={{ item.picture.url}}>
     {% endif %}
     </td>
     <td style="width:20%">
       {{ item.name }}<br>{{ item.price }}円
     </td>
     <td>
       {{ item.quantity }}個<br>
       {% if not item.in_stock %}
         在庫数を超えています。変更してください
       {% endif %}
     </td>
     <td align="right">
       <a class="btn btn-primary" href="{% url 'stores:update_cart' pk=item.id %}">変更する</a>
       <a class="btn btn-danger" href="{% url 'stores:delete_cart' pk=item.id %}">削除する</a>
     </td>
   </tr>
{% endfor %}
</tbody>
</table>
<hr>
<h3 class="offset-9">合計：{{ total_price }}円</h3>
<a class="offset-9 btn btn-secondary" href="{% url 'stores:input_address' %}">住所を入力する</a>
{% else %}
<h2>カートの中に商品が入っていません</h2>
{% endif %}
</div>
{% endblock %}

ecsite_project/templates/stores/confirm_order.html
{% extends 'base.html' %}
{% block content %}
<p>{{ user.username }}さん、注文の確認をお願いします</p>
<p>郵便番号:{{ address.zip_code }}</p>
<p>都道府県:{{ address.prefecture }}</p>
<p>住所:{{ address.address }}</p>
<table>
<tbody>
  {% for item in items %}
    <tr>
        <td style="width:20%">
            {% if item.picture %}
                <img width="75px" height="75px" src={{ item.picture.url }}>
            {% endif %}
        </td>
        <td style="width:20%">{{ item.name }}<br>{{item.price}}円</td>
        <td align="right">{{ item.quantity }}個</td>
    </tr>
  {% endfor %}
</tbody>
</table>
<hr>
<p><a href="{% url 'stores:cart_items' %}">カートへ</a></p>
<p><a href="{% url 'stores:input_address' %}">住所の入力へ</a></p>
<h3 class="offset-9">合計：{{ total_price}}円</h3>
<br>
<form method="POST" class="offset-10">
{% csrf_token %}
<input type="submit" class="btn btn-primary" value="注文を確定する">
</form>
{% endblock %}

ecsite_project/templates/stores/delete_cart.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ object.product.name }}をカートから削除しますか？</h2>
<form method="POST">
{% csrf_token %}
<input type="submit" value="削除">
</form>
{% endblock %}

ecsite_project/templates/stores/input_address.html
{% extends 'base.html' %}
{% block content %}
<div class="col-10 offset-1">
  <h2>住所を設定してください</h2>
  <hr>
  <form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="住所を設定する">
  </form>
  <hr>
  <h3>過去に利用したアドレス</h3>
  {% for address in addresses %}
    <p><a href={% url 'stores:input_address' pk=address.id %}>{{ address }}</a></p>
  {% endfor %}
  </hr>
</div> 
{% endblock %}

ecsite_project/templates/stores/order_success.html
{% extends 'base.html' %}
{% block content %}
<h2>注文を受け付けました</h2>
{% endblock %}

ecsite_project/templates/stores/product_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-6 offset-3">
   <div style="float: left;padding:0 20px 20px 0">
   {% for picture in object.productpictures_set.all %}
     {% if forloop.first %}
       <div><img width="200px" height="200px" src={{ picture.picture.url }}></div>
     {% else %}
       <img width="50px" height="50px" src={{ picture.picture.url }}>
     {% endif %}
   {% endfor %}
   </div>
   <div>
     <p>商品名：{{ object.name}} </p>
     <p>値段：{{ object.price}} </p>
     <p>残量：{{ object.stock}} </p>
     {% if object.stock %}
       {% if is_added %}
         <p class="btn btn-danger">カートに追加済みです</p>
       {% else %}
          <input type="number" id="quantity" name="quantity" min="1" max="{{ object.stock }}"><br>
          <button id="add_product" type="button" class="btn btn-primary">カートに追加</button>
       {% endif %}
     {% endif %}
     <input name="csrfToken" value="{{ csrf_token }}" type="hidden">
   </div>
</div>
<script>
$('#add_product').click(function(){
    var quantity = $("#quantity").val();
    var token = $('input[name="csrfToken"]').attr('value');
    $.ajaxSetup({
        beforeSend: function(xhr){
            xhr.setRequestHeader('X-CSRFToken',token);
        }
    })
    $.ajax({
        url: "{% url 'stores:add_product' %}",
        type:"POST",
        data: {product_id: "{{object.id}}",quantity:quantity},
        dataType:"json",
        success: function(json){
            if(json.message){
                $('#add_priduct').attr('class','btn btn-danger');
                $('#add_product').html('カートに登録済みです');
                $('#add_product').prop('disabled',true);
                alert(json.message);
            }
        },
        error: function(error){
            alert(error.responseJSON.message);
        }
    });
});
</script>
{% endblock %}

ecsite_project/templates/stores/product_list.html
{% extends 'base.html' %}
{% block content %}
<div class="col-10 offset-1">
<h2>商品一覧</h2>
<form method="get" action="{% url 'stores:product_list' %}">
  <p>商品タイプ: <input type="text" name="product_type_name" value="{{ product_type_name }}"/></p>
  <p>商品名: <input type="text" name="product_name" value="{{ product_name }}"/></p>
  <p>値段で並び替える：
     昇順<input type="radio" name="order_by_price" value="1" {% if ascending %}checked{% endif %}>
     降順<input type="radio" name="order_by_price" value="2" {% if descending %}checked{% endif %}>  
  </p>
  <p> <input type="submit" value="実行する"/></p>
</form>
<table class="table table-striped table-borderd">
<thead>
  <tr>
    <td>種類</td>
    <td>製品名</td>
    <td>値段</td>  
    <td>在庫数</td>
    <td>製造元</td>
  </tr>
</thead>
<tbody>
{% for product in object_list %}
  <tr>
    <td>{{ product.product_type.name }}</td>
    <td><a href="{% url 'stores:product_detail' pk=product.id %}">{{ product.name }}</td>
    <td>{{ product.price }}円</td>
    <td>{{ product.stock }}個</td>
    <td>{{ product.manufacturer.name }}</td>
  </tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}

ecsite_project/templates/stores/update_cart.html
{% extends 'base.html' %}
{% block content %}
<p>{{ object.product.name }}:在庫{{ object.product.stock }}</p>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="更新">
</form>

{% endblock %}